export const CATEGORIES = {
  全部: 'all',
  表单: 'form',
  功能: 'functional',
  布局: 'layout',
  动画: 'animation',
  高级: 'advanced',
  页面: 'pages',
} as const

export type CategoryKey = keyof typeof CATEGORIES
export type CategoryValue = (typeof CATEGORIES)[keyof typeof CATEGORIES]

export const COMPONENT_CATEGORIES: Record<string, CategoryValue> = {
  // form
  form: 'form',
  input: 'form',
  textarea: 'form',
  checkbox: 'form',
  radio: 'form',
  switch: 'form',
  select: 'form',
  uploader: 'form',
  slider: 'form',
  chatinput: 'form',
  searchbar: 'form',

  // functional
  button: 'functional',
  badge: 'functional',
  dropdown: 'functional',
  menu: 'functional',
  message: 'functional',
  modal: 'functional',
  pagination: 'functional',
  progress: 'functional',
  tabs: 'functional',
  tooltip: 'functional',
  tourguide: 'functional',
  loading: 'functional',
  icon: 'functional',
  rmbtn: 'functional',

  // layout
  card: 'layout',
  drawer: 'layout',
  popover: 'layout',
  sidebar: 'layout',
  keepalive: 'layout',
  splitline: 'layout',
  slot: 'layout',
  border: 'layout',
  gridbg: 'layout',
  phoneframe: 'layout',

  // animation
  animate: 'animation',
  aurora: 'animation',
  autoscrollanimate: 'animation',
  bgpaths: 'animation',
  carousel: 'animation',
  carousel3d: 'animation',
  flipitem: 'animation',
  heroentertext: 'animation',
  imgtransition: 'animation',
  liquidglass: 'animation',
  textfadein: 'animation',
  textreveal: 'animation',
  transitionitem: 'animation',
  seamlessscroll: 'animation',
  typewriter: 'animation',
  gradienttext: 'animation',
  glowclock: 'animation',
  dybgc: 'animation',

  // advanced
  codemirroreditor: 'advanced',
  mdeditor: 'advanced',
  htmlpreview: 'advanced',
  moveable: 'advanced',
  sortable: 'advanced',
  videotimeline: 'advanced',
  virtualizedmarkdown: 'advanced',
  virtualscroll: 'advanced',
  virtualwaterfall: 'advanced',
  infinitescroll: 'advanced',
  lazyimg: 'advanced',
  pagesnapshots: 'advanced',
  smartselection: 'advanced',
  noteboard: 'advanced',
  cutoutimg: 'advanced',
  discount: 'advanced',
  macrabdot: 'advanced',
  mask: 'advanced',
  previewimg: 'advanced',
  retryimg: 'advanced',
  textoverflow: 'advanced',

  // pages
  aisnake: 'pages',
  canvascomposite: 'pages',
  chat: 'pages',
  fabriceditor: 'pages',
  ffmpeg: 'pages',
  i18n: 'pages',
  motionprinciples: 'pages',
  perlinnoise: 'pages',
  pricing: 'pages',
  pyramidingtradingcalc: 'pages',
  scrollanimate: 'pages',
  scrolltrigger: 'pages',
  starport: 'pages',
  trainmodel: 'pages',
  usegetstatetest: 'pages',
  zoomcvs: 'pages',
}
