/**
 * 页面描述配置
 */

/**
 * 页面描述映射
 */
export const PAGE_DESCRIPTIONS: Record<string, string> = {
  aiSnake: '基于 Q-Learning 算法的 AI 贪吃蛇游戏，展示机器学习在游戏中的应用',
  canvasComposite: 'Canvas 图像合成工具，支持多种混合模式和滤镜效果',
  chat: '现代化聊天界面，支持消息发送、文件上传和实时通信',
  fabricEditor: '基于 Fabric.js 的在线图形编辑器，支持图形绘制和编辑',
  ffmpeg: '基于 FFmpeg.wasm 的视频处理工具，支持格式转换和编辑',
  i18n: '国际化演示页面，展示多语言切换和本地化功能',
  motionPrinciples: '动画原理展示，包含缓动函数和动画效果演示',
  perlinNoise: '柏林噪声算法可视化，展示程序化生成技术',
  pricing: '产品定价页面，展示现代化的价格展示和选择界面',
  pyramidingTradingCalc: '金字塔交易计算器，用于金融交易策略分析',
  scrollAnimate: '滚动动画演示，展示各种滚动触发的动画效果',
  scrollTrigger: '滚动触发器组件，实现复杂的滚动交互效果',
  starport: 'Starport 页面切换演示，展示流畅的页面过渡效果',
  trainModel: '机器学习模型训练演示，展示 TensorFlow.js 的应用',
  useGetStateTest: 'useGetState Hook 测试页面，展示状态管理解决方案',
  zoomCvs: 'Canvas 缩放和交互演示，展示画布操作和缩放功能',
}

/**
 * 组件描述映射
 */
export const COMPONENT_DESCRIPTIONS: Record<string, string> = {
  Button: '现代化按钮组件，支持多种样式和交互状态',
  Input: '表单输入组件，支持验证和多种输入类型',
  Card: '卡片容器组件，用于内容展示和布局',
  Modal: '模态对话框组件，支持自定义内容和动画',
  Dropdown: '下拉选择组件，支持搜索和多选功能',
  Pagination: '分页组件，支持自定义样式和跳转功能',
  Slider: '滑块组件，支持范围选择和自定义样式',
  Switch: '开关组件，支持自定义样式和禁用状态',
  Checkbox: '复选框组件，支持不确定状态和自定义样式',
  Radio: '单选框组件，支持分组和自定义样式',
  Select: '选择器组件，支持搜索、多选和自定义选项',
  Uploader: '文件上传组件，支持拖拽上传和进度显示',
  Form: '表单组件，支持验证和多种表单控件',
  Tabs: '标签页组件，支持动态添加和自定义样式',
  Tooltip: '工具提示组件，支持多种定位和自定义内容',
  Message: '消息提示组件，支持多种类型和自动关闭',
  Loading: '加载组件，支持自定义动画和文本',
  Progress: '进度条组件，支持多种样式和动画效果',
  Badge: '徽章组件，用于显示状态和数量',
  Drawer: '抽屉组件，支持多种方向和自定义内容',
  Popover: '弹出层组件，支持多种定位和自定义内容',
  Sidebar: '侧边栏组件，支持折叠和自定义内容',
  KeepAlive: '缓存组件，用于保持组件状态',
  Border: '边框组件，支持多种样式和动画效果',
  GridBg: '网格背景组件，支持自定义样式和动画',
  PhoneFrame: '手机框架组件，用于移动端预览',
  PixelStyle: '像素风格组件，展示复古游戏风格',
  SplitPane: '可调整大小的分割面板组件，支持多栏布局',
  Animate: '动画组件，支持多种动画效果',
  Aurora: '极光效果组件，展示动态背景效果',
  AutoScrollAnimate: '自动滚动动画组件',
  BgPaths: '背景路径动画组件',
  Carousel: '轮播图组件，支持多种切换效果',
  Carousel3D: '3D 轮播图组件，支持立体效果',
  FlipItem: '翻转项目组件，支持 3D 翻转效果',
  HeroEnterText: '英雄入场文字组件，支持打字机效果',
  ImgTransition: '图片过渡组件，支持多种切换效果',
  LiquidGlass: '液体玻璃效果组件',
  TextFadeIn: '文字淡入组件，支持多种动画效果',
  TextReveal: '文字揭示组件，支持滚动触发',
  TransitionItem: '过渡项目组件，支持多种过渡效果',
  SeamlessScroll: '无缝滚动组件，支持水平和垂直滚动',
  Typewriter: '打字机效果组件，支持自定义速度',
  GradientText: '渐变文字组件，支持多种渐变效果',
  GlowClock: '发光时钟组件，展示动态时间效果',
  DyBgc: '动态背景组件，支持多种背景效果',
  CodeMirrorEditor: '代码编辑器组件，基于 CodeMirror',
  MdEditor: 'Markdown 编辑器组件，支持实时预览',
  HtmlPreview: 'HTML 预览组件，支持语法高亮',
  Moveable: '可移动组件，支持拖拽和调整大小',
  Sortable: '可排序组件，支持拖拽排序',
  VideoTimeline: '视频时间轴组件，支持视频编辑',
  VirtualizedMarkdown: '虚拟化 Markdown 组件，支持大文件渲染',
  VirtualScroll: '虚拟滚动组件，支持大数据列表',
  VirtualWaterfall: '虚拟瀑布流组件，支持无限滚动',
  InfiniteScroll: '无限滚动组件，支持自动加载',
  LazyImg: '懒加载图片组件，支持占位符',
  PageSnapshots: '页面截图组件，用于组件展示',
  SmartSelection: '智能选择组件，支持多种选择模式',
  NoteBoard: '笔记板组件，支持实时协作',
  CutoutImg: '抠图组件，支持背景移除',
  Discount: '折扣组件，用于价格展示',
  TitleBarButtons: '窗口控制按钮，macOS 红绿灯风格',
  Mask: '遮罩组件，支持多种遮罩效果',
  PreviewImg: '图片预览组件，支持放大和缩放',
  RetryImg: '重试图片组件，支持加载失败重试',
  TextOverflow: '文字溢出组件，支持省略号显示',
  ChatInput: '聊天输入组件，支持表情和文件上传',
  SearchBar: '搜索栏组件，支持快捷键和过滤',
  TourGuide: '导览指南组件，支持步骤引导',
  Steps: '步骤组件，支持进度显示',
  NavBar: '导航栏组件，支持响应式设计和菜单折叠',
  Arrow: '箭头组件，支持多种方向和样式',
  CountdownRing: '倒计时环形组件，支持自定义时间和样式',
  BlurBgImg: '模糊背景图片组件，支持动态模糊效果',
  VirtualDyScroll: '动态虚拟滚动组件，支持动态高度列表',
  TanstackVirtual: 'TanStack Virtual 虚拟列表族：动态高度 + 无限加载的基础列表，与支持收放动画/收起预览/组内分页的分组列表',
  Landing: '着陆页组件，支持多种布局和动画效果',
  PageSwiper: '滑动导航组件，支持触摸滑动、按钮切换和指示器显示',
  TaskBanner: '任务状态彩条组件，最新在上堆叠，失败持久可重试，超量收拢为汇总条',
  BottomGlow: '由外部归一化强度驱动的通用容器底部光效',
}

/**
 * 页面分类映射
 */
export const PAGE_CATEGORY_MAP: Record<string, string> = {
  ai: 'AI 相关',
  canvas: '画布相关',
  chat: '聊天相关',
  editor: '编辑器',
  ffmpeg: '视频处理',
  motion: '动画效果',
  noise: '噪声算法',
  pricing: '定价页面',
  product: '产品相关',
  theme: '主题相关',
  scroll: '滚动相关',
  test: '测试页面',
  virtual: '虚拟化',
  zoom: '缩放相关',
}

/**
 * 组件分类映射
 */
export const COMPONENT_CATEGORY_MAP: Record<string, string> = {
  form: '表单组件',
  functional: '功能组件',
  layout: '布局组件',
  animation: '动画组件',
  advanced: '高级组件',
  pages: '页面组件',
}

/**
 * 组件名称映射（用于显示名称格式化）
 */
export const COMPONENT_NAME_MAP: Record<string, string> = {
  aiSnake: 'AI 贪吃蛇',
  ffmpeg: 'FFmpeg 工具',
  ffmpegDemo: 'FFmpeg 演示',
  i18n: '国际化',
  keepAliveTest: 'Keep Alive 测试',
  scrollAnimate: '滚动动画',
  useGetStateTest: 'useGetState 测试',
  zoomCvs: '缩放画布',
  canvasComposite: '画布合成',
  trainModel: '训练模型',
  MotionPrinciples: '动画原理',
  PerlinNoise: '柏林噪声',
  ProductGenerator: '产品生成器',
  VirtualWaterfall: '虚拟瀑布流',
  VirtualScroll: '虚拟滚动',
  VirtualDyScroll: '动态虚拟滚动',
  TanstackVirtual: 'TanStack 虚拟列表',
  VirtualizedMarkdown: '虚拟化 Markdown',
  AutoScrollAnimate: '自动滚动动画',
  BlurBgImg: '模糊背景图',
  CutoutImg: '裁剪图片',
  DisCount: '折扣组件',
  DyBgc: '动态背景',
  FlipItem: '翻转项目',
  GlowClock: '发光时钟',
  GradientBoundary: '渐变边框',
  GradientText: '渐变文字',
  TaskBanner: '任务状态彩条',
  BottomGlow: '底部动态光效',
  GridBg: '网格背景',
  HeroEnterText: '英雄入场文字',
  HtmlPreview: 'HTML 预览',
  ImgTransition: '图片过渡',
  InfiniteScroll: '无限滚动',
  InteractiveEmoji: '交互表情',
  LazyImg: '懒加载图片',
  LiquidGlass: '液体玻璃',
  TitleBarButtons: '窗口控制按钮',
  MdEditor: 'Markdown 编辑器',
  NavBar: '导航栏',
  PixelStyle: '像素风格',
  PreviewImg: '预览图片',
  RetryImg: '重试图片',
  closeBtn: '关闭按钮',
  SeamlessScroll: '无缝滚动',
  SearchBar: '搜索栏',
  SmartSelection: '智能选择',
  SplitText: '分割文字',
  SplitPane: '可调整大小面板',
  TextFadeIn: '文字淡入',
  TextOverflow: '文字溢出',
  TextReveal: '文字揭示',
  ThemeToggle: '主题切换',
  ThinkingStep: '思考步骤',
  TourGuide: '导览指南',
  TransitionItem: '过渡项目',
  Typewriter: '打字机效果',
  VideoTimeline: '视频时间轴',
  PageSwiper: '滑动导航',
}
