export type FilterType
  = | 'fadeIn'
    | 'cool'
    | 'grayscale'
    | 'warm'
    | 'vintage'
    | 'sketch'
    | 'sharp'
    | 'fisheye'
    | 'horizontalMirror'
    | 'eq'
    | 'blur'
    | 'rotate'
    | 'text'
